import type { GeneratedImage } from "../domain";
import { ProviderConfigurationError, ProviderRequestError, type ImageGenerationPort, type ImageGenerationRequest, type ImageGenerationSubmission, type ImageGenerationPollResult } from "../ports";
type ErrorPayload = { error?: { message?: string } };
type SubmissionPayload = ErrorPayload & { data?: Array<{ task_id?: string }> };
type TaskPayload = ErrorPayload & { data?: { id?: string; status?: "submitted" | "queued" | "processing" | "completed" | "failed"; result?: { images?: Array<{ url?: string[] }> } } };
export type APIMartAdapterOptions = { apiKey: string; baseUrl: string; model: string; fetch?: typeof globalThis.fetch; pollIntervalMs?: number; maxPolls?: number; requestTimeoutMs?: number; delay?: (milliseconds: number, signal?: AbortSignal) => Promise<void> };
const sizeToAspectRatio = { "1024x1024": "1:1", "1536x1024": "3:2", "1024x1536": "2:3" } as const;
const wait = (milliseconds: number, signal?: AbortSignal) => new Promise<void>((resolve, reject) => { const timer = setTimeout(resolve, milliseconds); signal?.addEventListener("abort", () => { clearTimeout(timer); reject(signal.reason ?? new DOMException("Aborted", "AbortError")); }, { once: true }); });
export class APIMartImageGenerationAdapter implements ImageGenerationPort {
  readonly provider = "apimart";
  readonly capabilities = { textToImage: true, referenceImages: true, asyncJobs: true, maxReferenceImages: 16 } as const;
  private readonly request: typeof globalThis.fetch;
  constructor(private readonly options: APIMartAdapterOptions) { if (!options.apiKey || !options.baseUrl || !options.model) throw new ProviderConfigurationError("APIMart server configuration is incomplete"); this.request = options.fetch ?? globalThis.fetch; }
  async generate(input: Parameters<ImageGenerationPort["generate"]>[0], signal?: AbortSignal): Promise<GeneratedImage[]> {
    const submitted = await this.submit({ prompt: input.prompt, size: input.size, quality: input.quality }, signal); if (!submitted.providerTaskId) throw new ProviderRequestError("APIMart returned no task identifier", "apimart", false);
    for (let poll = 0; poll < (this.options.maxPolls ?? 60); poll += 1) { await (this.options.delay ?? wait)(this.options.pollIntervalMs ?? 2_000, signal); const result = await this.poll(submitted.providerTaskId, signal); if (result.status === "failed") throw new ProviderRequestError(result.error ?? "APIMart image task failed", "apimart", false); if (result.status === "completed") return result.images ?? []; }
    throw new ProviderRequestError("APIMart image task timed out", "apimart", true, 408);
  }
  async submit(input: ImageGenerationRequest, signal?: AbortSignal): Promise<ImageGenerationSubmission> {
    const referenceImages = input.referenceImages?.map(({ bytes, mimeType }) => `data:${mimeType};base64,${Buffer.from(bytes).toString("base64")}`);
    const response = await this.requestWithTimeout(new URL("v1/images/generations", ensureTrailingSlash(this.options.baseUrl)), { method: "POST", headers: { authorization: `Bearer ${this.options.apiKey}`, "content-type": "application/json" }, body: JSON.stringify({ model: this.options.model, prompt: input.prompt, n: 1, ...(input.size && input.size !== "auto" && !referenceImages?.length ? { size: sizeToAspectRatio[input.size] } : {}), resolution: input.quality === "high" ? "2k" : "1k", ...(referenceImages?.length ? { image_urls: referenceImages } : {}) }), signal });
    const payload = await response.json().catch(() => ({})) as SubmissionPayload; if (!response.ok) throw requestError(response.status, payload, "submission"); const providerTaskId = payload.data?.[0]?.task_id; if (!providerTaskId) throw new ProviderRequestError("APIMart returned no task identifier", "apimart", false); return { status: "submitted", providerTaskId };
  }
  async poll(providerTaskId: string, signal?: AbortSignal): Promise<ImageGenerationPollResult> {
    const response = await this.requestWithTimeout(new URL(`v1/tasks/${encodeURIComponent(providerTaskId)}?language=zh`, ensureTrailingSlash(this.options.baseUrl)), { headers: { authorization: `Bearer ${this.options.apiKey}` }, signal }); const payload = await response.json().catch(() => ({})) as TaskPayload; if (!response.ok) throw requestError(response.status, payload, "status check"); if (payload.data?.status === "failed") return { status: "failed", providerTaskId, error: "APIMart image task failed" }; if (payload.data?.status !== "completed") return { status: "pending", providerTaskId }; const urls = payload.data.result?.images?.flatMap((image) => image.url ?? []) ?? []; if (!urls.length) return { status: "failed", providerTaskId, error: "APIMart completed without image candidates" }; return { status: "completed", providerTaskId, images: urls.map((remoteUrl) => ({ mimeType: "image/png", remoteUrl, providerRequestId: payload.data?.id ?? providerTaskId })) };
  }
  private async requestWithTimeout(url: URL, init: RequestInit): Promise<Response> { const timeoutMs = this.options.requestTimeoutMs ?? 30_000; const controller = new AbortController(); const parentSignal = init.signal; const abort = () => controller.abort(parentSignal?.reason); if (parentSignal?.aborted) abort(); else parentSignal?.addEventListener("abort", abort, { once: true }); const timer = setTimeout(() => controller.abort(new Error("APIMart request timed out")), timeoutMs); try { return await this.request(url, { ...init, signal: controller.signal }); } catch (error) { if (controller.signal.aborted && !parentSignal?.aborted) throw new ProviderRequestError("APIMart request timed out", "apimart", true, 408); throw error; } finally { clearTimeout(timer); parentSignal?.removeEventListener("abort", abort); } }
}
const requestError = (status: number, payload: ErrorPayload, phase: string) => new ProviderRequestError(payload.error?.message ?? `APIMart ${phase} failed`, "apimart", status === 408 || status === 429 || status >= 500, status);
const ensureTrailingSlash = (value: string) => value.endsWith("/") ? value : `${value}/`;
export const createAPIMartAdapterFromEnvironment = () => new APIMartImageGenerationAdapter({ apiKey: process.env.APIMART_API_KEY ?? "", baseUrl: process.env.APIMART_BASE_URL ?? "https://api.apimart.ai", model: process.env.APIMART_IMAGE_MODEL ?? "gpt-image-2" });
